### ISSUE TITLE
why don't you write down 'gitignore'

### ISSUE THREAD

**Issue by Alghost** [availbit/blog#3]
Why don't you write down 'gitignore';

**/*.pyc
**/_ _ pycache _ _

Probably as you know the file and directory, these are created when you run python code as module automatically.
and It doesn't need to be managed. so ..  ! :D

**Comment by availbit** [comment]
Oh, It's my fault. thank you!

**Comment by Alghost** [comment]
Do you know that you don't post the gitignore yet? :D
